### ISSUE TITLE
Check should return UNKNOWN on error

### ISSUE THREAD

**Issue by fractalcat** [anchor/haskell-nagios-checks#6]
At the moment, the check just crashes if it can't reach the rabbit server or can't parse the response. It should not do this; it should instead add a check result of type UNKNOWN, the error message as infotext, and exit normally.

**Comment by glasnt** [comment]
Fixed previously by changing the main function to be a wrapper for NagiosPlugin() and using that package's functionality to return any unknown errors as UNKNOWN errors.
